packages:
  - 'apps/*'
  - 'packages/*'

overrides:
  vue: 3.5.35

allowBuilds:
  esbuild: true
  msw: true
  vue-demi: true

patchedDependencies:
  '@vueuse/core@14.3.0': patches/@vueuse__core@14.3.0.patch
